create table tb_perfil (
    id bigint generated by default as identity,
    descricao varchar(20) not null,
    primary key (id)
);

create table tb_usuario (
    id bigint generated by default as identity,
    username varchar(60) not null,
    senha varchar(100) not null,
    nome_exibicao varchar(100) not null,
    ativo boolean not null default true,
    data_criacao date not null,
    id_tutor bigint,
    primary key (id)
);

create table tb_usuario_perfil (
    id_usuario bigint not null,
    id_perfil bigint not null,
    primary key (id_usuario, id_perfil)
);

create table tb_tutor (
    id bigint generated by default as identity,
    nome varchar(100) not null,
    cpf varchar(11) not null,
    email varchar(150) not null,
    telefone varchar(11) not null,
    data_nascimento date not null,
    ativo boolean not null default true,
    primary key (id)
);

create table tb_clinica (
    id bigint generated by default as identity,
    nome varchar(150) not null,
    cnpj varchar(14) not null,
    telefone varchar(11) not null,
    email varchar(150) not null,
    endereco varchar(300) not null,
    cidade varchar(100) not null,
    estado varchar(2) not null,
    ativo boolean not null default true,
    primary key (id)
);

create table tb_pet (
    id bigint generated by default as identity,
    nome varchar(80) not null,
    especie varchar(20) not null,
    raca varchar(80) not null,
    data_nascimento date not null,
    peso_kg decimal(6,2),
    sexo varchar(10),
    castrado boolean,
    microchip varchar(20),
    observacoes varchar(500),
    ativo boolean not null default true,
    id_tutor bigint not null,
    id_clinica_principal bigint,
    primary key (id)
);

create table tb_consulta (
    id bigint generated by default as identity,
    data_consulta date not null,
    status varchar(20) not null,
    tipo_consulta varchar(30) not null,
    veterinario varchar(100) not null,
    diagnostico varchar(1000),
    prescricao varchar(1000),
    observacoes varchar(500),
    valor decimal(10,2),
    data_retorno date,
    criado_em timestamp not null,
    id_pet bigint not null,
    id_clinica bigint not null,
    primary key (id)
);

create table tb_evento_saude (
    id bigint generated by default as identity,
    tipo_evento varchar(30) not null,
    descricao varchar(500) not null,
    data_evento date not null,
    data_proxima_acao date,
    concluido boolean not null default false,
    criado_em timestamp not null,
    id_pet bigint not null,
    id_consulta bigint,
    primary key (id)
);

create table tb_vacina (
    id bigint generated by default as identity,
    nome varchar(100) not null,
    fabricante varchar(100) not null,
    lote varchar(50),
    data_aplicacao date not null,
    data_validade date not null,
    proxima_dose date,
    criado_em timestamp not null,
    id_pet bigint not null,
    id_clinica bigint,
    primary key (id)
);

create table tb_medicamento (
    id bigint generated by default as identity,
    nome varchar(100) not null,
    principio_ativo varchar(100),
    dosagem varchar(100) not null,
    frequencia varchar(100) not null,
    data_inicio date not null,
    data_fim date,
    uso_continuo boolean not null default false,
    observacoes varchar(500),
    id_pet bigint not null,
    id_consulta bigint,
    primary key (id)
);
